maps:
  endpoint: http://localhost:9191
pricing:
  endpoint: http://localhost:8084

spring:
  application:
    name: vehicle-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
