maps:
  endpoint: http://localhost:9191
pricing:
  serviceName: pricing-service

spring:
  application:
    name: vehicle-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

springdoc:
  swaggerUi:
    path: /swagger-ui.html
