spring:
  application:
    name: pricing-service

  data:
    rest:
      basePath: /services

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
