spring:
  application:
    name: eureka-server

logging:
  level:
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
